_core:
  default_config_hash: YpBA3MmDuJpZ9SM3DE4kR0lTY89bf2y3g0sS7s3TQ4k
always_save_userinfo: true
connect_existing_users: true
override_registration_settings: false
user_login_display: above
userinfo_mappings:
  timezone: zoneinfo
generic:
  enabled: true
  settings:
    client_id: 019b79d1-29cd-7078-8662-d4413a597a1f
    client_secret: b07a4872198a4b9a2949a91a37ed3cfe65a1214aa552b66b37c1b9d928efc5b1
    authorization_endpoint: 'https://admin.soilsync.shop/oauth/authorize'
    token_endpoint: 'https://admin.soilsync.shop/oauth/token'
    userinfo_endpoint: 'https://admin.soilsync.shop/api/user'
redirect_url: /dashboard
